# for local development
version: '3.7'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: matheushenrique35/app-financas
    container_name: appfinancas
    ports:
      - '8070:80'

