version: '3'

services:

  mongo:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: my_db
      MONGO_INITDB_ROOT_USERNAME: teste
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongodbvolume:/data/db

volumes:
  mongodbvolume:
    driver: local
